package entity;
// Generated Mar 16, 2020 2:43:58 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private String username;
     private String password;
     private boolean type;
     private String fullname;
     private boolean gender;
     private String birthday;
     private String phone;
     private String email;
     private String class_;
     private Set examResults = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(String username, String password, boolean type, String fullname, boolean gender, String birthday, String phone, String email) {
        this.username = username;
        this.password = password;
        this.type = type;
        this.fullname = fullname;
        this.gender = gender;
        this.birthday = birthday;
        this.phone = phone;
        this.email = email;
    }
    public Accounts(String username, String password, boolean type, String fullname, boolean gender, String birthday, String phone, String email, String class_, Set examResults) {
       this.username = username;
       this.password = password;
       this.type = type;
       this.fullname = fullname;
       this.gender = gender;
       this.birthday = birthday;
       this.phone = phone;
       this.email = email;
       this.class_ = class_;
       this.examResults = examResults;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isType() {
        return this.type;
    }
    
    public void setType(boolean type) {
        this.type = type;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public Set getExamResults() {
        return this.examResults;
    }
    
    public void setExamResults(Set examResults) {
        this.examResults = examResults;
    }




}


