package entity;
// Generated Mar 16, 2020 2:43:58 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private int id;
     private String q;
     private String aa;
     private String ab;
     private String ac;
     private String ad;
     private String answer;
     private Set examDetails = new HashSet(0);

    public Questions() {
    }

	
    public Questions(int id, String q, String aa, String ab, String ac, String ad, String answer) {
        this.id = id;
        this.q = q;
        this.aa = aa;
        this.ab = ab;
        this.ac = ac;
        this.ad = ad;
        this.answer = answer;
    }
    public Questions(int id, String q, String aa, String ab, String ac, String ad, String answer, Set examDetails) {
       this.id = id;
       this.q = q;
       this.aa = aa;
       this.ab = ab;
       this.ac = ac;
       this.ad = ad;
       this.answer = answer;
       this.examDetails = examDetails;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getQ() {
        return this.q;
    }
    
    public void setQ(String q) {
        this.q = q;
    }
    public String getAa() {
        return this.aa;
    }
    
    public void setAa(String aa) {
        this.aa = aa;
    }
    public String getAb() {
        return this.ab;
    }
    
    public void setAb(String ab) {
        this.ab = ab;
    }
    public String getAc() {
        return this.ac;
    }
    
    public void setAc(String ac) {
        this.ac = ac;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Set getExamDetails() {
        return this.examDetails;
    }
    
    public void setExamDetails(Set examDetails) {
        this.examDetails = examDetails;
    }




}


