package entity;
// Generated Mar 16, 2020 2:43:58 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Class generated by hbm2java
 */
public class Class  implements java.io.Serializable {


     private String id;

    public Class() {
    }

    public Class(String id) {
       this.id = id;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }




}


