package entity;
// Generated Mar 16, 2020 2:43:58 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam  implements java.io.Serializable {


     private String id;
     private String testDay;
     private Set examResults = new HashSet(0);
     private Set examDetails = new HashSet(0);

    public Exam() {
    }

	
    public Exam(String id, String testDay) {
        this.id = id;
        this.testDay = testDay;
    }
    public Exam(String id, String testDay, Set examResults, Set examDetails) {
       this.id = id;
       this.testDay = testDay;
       this.examResults = examResults;
       this.examDetails = examDetails;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTestDay() {
        return this.testDay;
    }
    
    public void setTestDay(String testDay) {
        this.testDay = testDay;
    }
    public Set getExamResults() {
        return this.examResults;
    }
    
    public void setExamResults(Set examResults) {
        this.examResults = examResults;
    }
    public Set getExamDetails() {
        return this.examDetails;
    }
    
    public void setExamDetails(Set examDetails) {
        this.examDetails = examDetails;
    }




}


