/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.AccountDAO;
import DAO.ExamDAO;
import DAO.ExamResultDAO;
import entity.Accounts;
import entity.Exam;
import entity.ExamResult;
import entity.Questions;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author giap
 */
public class Form_LamDeThi extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Exam
     */
    List<Questions> list = new ArrayList<>();
    List<String> listA = new ArrayList<>();
    Timer t = null;
    int index = -1;
    String examID;
    Accounts acc;
    Exam exam;
    
    public Form_LamDeThi(String examID,Accounts acc) {
        initComponents();
        this.acc = acc;
        this.examID = examID;
        this.getData(examID);
        this.list0();
    }
    //Hiển thi câu hỏi
    public void display(){
        txtQuestion.setText("Câu "+(index+1)+": "+list.get(index).getQ());
        rbA.setText("A. "+list.get(index).getAa());
        rbA.setActionCommand("A");
        rbB.setText("B. "+list.get(index).getAb());
        rbB.setActionCommand("B");
        rbC.setText("C. "+list.get(index).getAc());
        rbC.setActionCommand("C");
        rbD.setText("D. "+list.get(index).getAd());
        rbD.setActionCommand("D");
       
        switch(listA.get(index)){
            case "A": rbA.setSelected(true); break;
            case "B": rbB.setSelected(true); break;
            case "C": rbC.setSelected(true); break;
            case "D": rbD.setSelected(true); break;
            default:buttonGroup1.clearSelection();
        }
    }
    //Cài đặt đồng hồ
    public void setTime(){
        t = new Timer(1000, (ActionEvent e) ->{
            int value = Integer.parseInt(txtTime.getText())-1;
            txtTime.setText(String.valueOf(value));
            if(value==0){
                t.stop();
                JOptionPane.showMessageDialog(this, "Rất tiếc, bạn đã hết thời gian làm bài");
                this.saveResult();
                btnNopbai.setEnabled(false);
            }
        });
        t.start();
    }
    //Lấy câu trả lời của người chơi
    public void getAnswerP(){
        
        if(index != -1 && buttonGroup1.getSelection()!=null){
            listA.set(index, buttonGroup1.getSelection().getActionCommand());
        }
    }
    //Tạo list câu trả lời rỗng
    public void list0(){
        for(int i = 0 ; i < list.size() ; i++){
            listA.add("");
        }
    }
    //Lấy list câu hỏi
    public void getData(String examID){
        exam = new ExamDAO().findOne(examID);
        list = new ExamDAO().getExamQuestion(examID);
        if(list==null || list.size()==0){
            JOptionPane.showMessageDialog(this, "RẤT TIẾC, GẶP LỖI TẢI DỮ LIỆU CÂU HỎI");
            return;
        }
    }
    //SetEnable cho các button
    public void setButton(){
        if(index == list.size()-1){
            btnSau.setEnabled(false);
        }else{
            btnSau.setEnabled(true);
        }
        if(index == 0){
            btnTruoc.setEnabled(false);
        }else{
            btnTruoc.setEnabled(true);
        }
    }
    public double getResult(){
        int count = 0;
        for(int i = 0; i < list.size() ;i++){
            if(listA.get(i).equals(list.get(i).getAnswer())){
                count++;
            }
        }
        JOptionPane.showMessageDialog(this, "BẠN TRẢ LỜI ĐÚNG "+count+"/"+list.size());
        return (count*10)/list.size();
        
    }
    public void saveResult(){
        ExamResult rs = new ExamResult();
        rs.setExam(exam);
        rs.setAccounts(acc);
        rs.setScore(getResult());
        String examday = String.valueOf(java.time.LocalDate.now());
        rs.setExamday(examday);
        if(new ExamResultDAO().save(rs)){
            JOptionPane.showMessageDialog(this, "KẾT QUẢ ĐÃ ĐƯỢC LƯU LẠI");
        }else{
            JOptionPane.showMessageDialog(this, "LỖI, KẾT QUẢ KHÔNG ĐƯỢC LƯU LẠI");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtQuestion = new javax.swing.JLabel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnTruoc = new javax.swing.JButton();
        btnSau = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTime = new javax.swing.JLabel();
        btnGO = new javax.swing.JButton();
        btnNopbai = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setMinimumSize(new java.awt.Dimension(708, 405));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtQuestion.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        txtQuestion.setForeground(new java.awt.Color(255, 51, 51));
        txtQuestion.setText("Đề bài");

        buttonGroup1.add(rbA);
        rbA.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        rbA.setText("Đáp án A");

        buttonGroup1.add(rbB);
        rbB.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        rbB.setText("Đáp án B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbC);
        rbC.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        rbC.setText("Đáp án C");

        buttonGroup1.add(rbD);
        rbD.setFont(new java.awt.Font("Roboto Condensed Light", 0, 14)); // NOI18N
        rbD.setText("Đáp án D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbA, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbB, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbD, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbC, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbD)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-first-30 (1).png"))); // NOI18N
        btnTruoc.setText("<< Câu trước");
        btnTruoc.setEnabled(false);
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnSau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-last-30 (1).png"))); // NOI18N
        btnSau.setText("Câu sau >>");
        btnSau.setEnabled(false);
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnSau, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTruoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTime.setFont(new java.awt.Font("Calculator", 1, 36)); // NOI18N
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTime.setText("600");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnGO.setBackground(new java.awt.Color(255, 102, 102));
        btnGO.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-next-30.png"))); // NOI18N
        btnGO.setText("Bắt đầu bài thi");
        btnGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGOActionPerformed(evt);
            }
        });

        btnNopbai.setBackground(new java.awt.Color(204, 204, 204));
        btnNopbai.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnNopbai.setForeground(new java.awt.Color(255, 51, 51));
        btnNopbai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Upload.png"))); // NOI18N
        btnNopbai.setText("Nộp Bài");
        btnNopbai.setEnabled(false);
        btnNopbai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopbaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnGO, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBActionPerformed

    private void btnGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGOActionPerformed
        // TODO add your handling code here:
        btnSau.setEnabled(true);
        btnNopbai.setEnabled(true);
        btnGO.setEnabled(false);
        this.setTime();
        index = 0 ;
        this.display();
        this.setButton();
        
        
        
    }//GEN-LAST:event_btnGOActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
        this.getAnswerP();
        index++;
        this.setButton();
        this.display();
    }//GEN-LAST:event_btnSauActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        this.getAnswerP();
        index--;
        this.setButton();
        this.display();
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnNopbaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopbaiActionPerformed
        // TODO add your handling code here:
        
        this.getAnswerP();   
        t.stop();
        btnNopbai.setEnabled(false);
        this.saveResult();
        
    }//GEN-LAST:event_btnNopbaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGO;
    private javax.swing.JButton btnNopbai;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnTruoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JLabel txtQuestion;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
