/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.ExamDAO;
import DAO.ExamDetailDAO;
import DAO.QuestionDAO;
import entity.Exam;
import entity.ExamDetail;
import entity.Questions;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giap
 */
public class Form_QLDeThi2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_QLDeThi2
     */
    
    Exam exam;
    List<ExamDetail> listED = new ArrayList<>();
    List<Questions> listQ = new ArrayList<>();
    DefaultTableModel model2;
    DefaultTableModel model;
    int index;
    ExamDetailDAO eDDAO = new ExamDetailDAO();
    public Form_QLDeThi2() {
        initComponents();
        model = (DefaultTableModel) tbl_danhsach.getModel();
        model2 = (DefaultTableModel) tbl_list2.getModel();
        listQ = new QuestionDAO().findAll();
        this.getCombobox();
        this.getData();
        this.fillToTable2();
    }
    public void getData(){
        listED.clear();
        listED = new ExamDetailDAO().listQfE(exam);
        if(exam.getStt()){
            jLabel8.setText("Đang mở");
            btn_stt.setEnabled(true);
            btn_addQ.setEnabled(true);
            btn_deleteQ.setEnabled(true);
            btn_addQ2.setEnabled(true);
        }else{
            jLabel8.setText("Đã khóa");
            btn_stt.setEnabled(false);
            btn_addQ.setEnabled(false);
            btn_deleteQ.setEnabled(false);
            btn_addQ2.setEnabled(false);
        }
        this.fillToTable();
    }
    
    public void getCombobox(){
        List<Exam> listE = new ExamDAO().findAll();
        cbo_examid.removeAllItems();
        
        if(listE!=null){
            for(Exam exam : listE){
                cbo_examid.addItem(exam.getId());
            }
        }
    }
    public void fillToTable(){
        model.setRowCount(0);
        int gg = 1;
        for (ExamDetail ed : listED) {
            model.addRow(new Object[]{gg, ed.getQuestions().getQ()});
            gg++;
        }
        if (listED.size() > 0) {
            index = 0;
            tbl_danhsach.setRowSelectionInterval(index, index);
        }
        lbl_soluong.setText(""+listED.size());
        lbl_examid.setText("ĐỀ THI : "+exam.getId());
   }
    public void fillToTable2(){
        model2.setRowCount(0);
        int gg = 1;
        for (Questions q : listQ) {
            model2.addRow(new Object[]{gg, q.getQ()});
            gg++;
        }
        if (listQ.size() > 0) {
            index = 0;
            tbl_list2.setRowSelectionInterval(index, index);
        }
    }
    public void deleteQ(){
        if(new ExamDetailDAO().delete(listED.get(index))){
            JOptionPane.showMessageDialog(this, "ĐÃ XÓA CÂU HỎI KHỎI ĐỀ THI THÀNH CÔNG");
        }else{
            JOptionPane.showMessageDialog(this, "XÓA THẤT BẠI");
        }
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhsach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbo_examid = new javax.swing.JComboBox<>();
        btn_addQ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_deleteQ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_stt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_addQ2 = new javax.swing.JButton();
        lbl_examid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_soluong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_debai = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_list2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_newE = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(724, 468));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("QUẢN LÝ ĐỀ THI");

        tbl_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "ĐỀ BÀI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_danhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhsach);
        if (tbl_danhsach.getColumnModel().getColumnCount() > 0) {
            tbl_danhsach.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_danhsach.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl_danhsach.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel1.setText("Đề Thi :");

        cbo_examid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_examidItemStateChanged(evt);
            }
        });

        btn_addQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btn_addQ.setText("Thêm Câu Hỏi");
        btn_addQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addQActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        jButton3.setText("XÓA ĐỀ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_deleteQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Task list.png"))); // NOI18N
        btn_deleteQ.setText("XÓA CÂU HỎI");
        btn_deleteQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteQActionPerformed(evt);
            }
        });

        jLabel7.setText("Trạng Thái :");

        jLabel8.setText("jLabel8");

        btn_stt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lock.png"))); // NOI18N
        btn_stt.setText("KHÓA");
        btn_stt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_examid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btn_deleteQ, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_addQ, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_examid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteQ)
                    .addComponent(btn_stt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh Sách Đề Thi", jPanel1);

        btn_addQ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Create.png"))); // NOI18N
        btn_addQ2.setText("Thêm Câu Hỏi Vào Đề");
        btn_addQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addQ2ActionPerformed(evt);
            }
        });

        lbl_examid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_examid.setForeground(new java.awt.Color(0, 0, 255));
        lbl_examid.setText("ĐỀ THI :");

        jLabel5.setText("Số lượng câu hỏi trong đề :");

        lbl_soluong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_soluong.setForeground(new java.awt.Color(255, 0, 0));
        lbl_soluong.setText("S");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jLabel2.setText("Đề bài :");

        jButton5.setText("Tìm Kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_debai, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton5)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_debai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_list2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "ĐỀ BÀI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_list2);
        if (tbl_list2.getColumnModel().getColumnCount() > 0) {
            tbl_list2.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel6.setText("Danh sách câu hỏi :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(lbl_examid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_examid, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_soluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thêm Câu Hỏi Vào Đề Thi", jPanel3);

        jLabel3.setText("Mã Đề Thi :");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Accept.png"))); // NOI18N
        jButton6.setText("Lưu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(txt_newE, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_newE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tạo Mới Đề Thi", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_examidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_examidItemStateChanged
        // TODO add your handling code here:
        String examID = (String) cbo_examid.getSelectedItem();
        exam = new ExamDAO().findOne(examID);
        this.getData();
        this.fillToTable();
    }//GEN-LAST:event_cbo_examidItemStateChanged

    private void btn_addQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addQActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel3);
    }//GEN-LAST:event_btn_addQActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "BẠN CÓ CHẮC CHẮN XÓA ĐỀ THI NÀY");
        if(choose==JOptionPane.YES_OPTION){
            if(new ExamDAO().delete(exam)){
                JOptionPane.showMessageDialog(this, "XÓA ĐỀ THI "+exam.getId()+" THÀNH CÔNG");
                cbo_examid.removeItem(exam.getId());
            }else{
                JOptionPane.showMessageDialog(this, "XÓA ĐỀ THI "+exam.getId()+" THẤT BẠI");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        listQ.clear();
        listQ = new QuestionDAO().search(txt_debai.getText());
        this.fillToTable2();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_addQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addQ2ActionPerformed
        // TODO add your handling code here:
        if(listED.size()==10){
            JOptionPane.showMessageDialog(this, "ĐỀ THI ĐÃ ĐẠT GIỚI HẠN VỀ CÂU HỎI LÀ 10, KHÔNG THỂ THÊM CÂU HỎI");
        }else{
            index  = tbl_list2.getSelectedRow();
            Questions newQ = listQ.get(index);
            ExamDetail newED = new ExamDetail();
            newED.setExam(exam);
            newED.setQuestions(newQ);
            if(new ExamDetailDAO().save(newED)){
                JOptionPane.showMessageDialog(this, "THÊM CÂU HỎI VÀO ĐỀ THÀNH CÔNG");
                this.getData();
                this.fillToTable();
            }else{
                JOptionPane.showMessageDialog(this, "THÊM CÂU HỎI VÀO ĐỀ THẤT BẠI");
            }
        }
        
    }//GEN-LAST:event_btn_addQ2ActionPerformed

    private void btn_deleteQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteQActionPerformed
        // TODO add your handling code here:
        index = tbl_danhsach.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "KHÔNG CÓ GÌ ĐỂ XÓA");
        }else{
            System.out.println(listED.get(index).getQuestions().getQ()+"------"+listED.get(index).getId());
        int input = JOptionPane.showConfirmDialog(this, "CÂU HỎI NÀY SẼ BỊ XÓA ĐỀ");
        if (input == JOptionPane.YES_OPTION) {
            if (listED.size() <= 0) {
                JOptionPane.showMessageDialog(this, "KHÔNG CÓ GÌ ĐỂ XÓA");
                return;
            }
        }
        
        if(new ExamDetailDAO().delete(listED.get(index))){
            listED.remove(index);
            model.removeRow(index);
            if (listED.size() > 0) {
                if (index == listQ.size()) {
                    index--;
                    tbl_danhsach.setRowSelectionInterval(index, index);
                }
            }
            lbl_soluong.setText(""+listED.size());
            JOptionPane.showMessageDialog(this, "ĐÃ XÓA CÂU HỎI KHỎI ĐỀ THI THÀNH CÔNG");
            this.fillToTable();
        }else{
            JOptionPane.showMessageDialog(this, "XÓA THẤT BẠI");
        }
        }
        
    }//GEN-LAST:event_btn_deleteQActionPerformed

    private void tbl_danhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhsachMouseClicked
        // TODO add your handling code here:
        index = tbl_danhsach.getSelectedRow();
    }//GEN-LAST:event_tbl_danhsachMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String newId = txt_newE.getText().trim();
        if(newId.length()<1 || newId.length()>10){
            JOptionPane.showMessageDialog(this, "MÃ ĐỀ PHẢI TỪ 1 ĐẾN 10 KÝ TỰ");
            return;
        }else{
            Exam newE = new ExamDAO().findOne(newId);
            if(newE != null){
                JOptionPane.showMessageDialog(this, "ĐỀ THI NÀY ĐÃ CÓ SẴN");
                return;
            }else{
                newE = new Exam();
                newE.setId(newId);
                newE.setStt(true);
                if(new ExamDAO().save(newE)){
                    cbo_examid.addItem(newId);
                    JOptionPane.showMessageDialog(this, "TẠO MỚI ĐỀ THI THÀNH CÔNG");
                }else{
                    JOptionPane.showMessageDialog(this, "TẠO MỚI ĐỀ THI THẤT BẠI");
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_sttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sttActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "ĐỀ THI BỊ KHÓA SẼ KHÔNG THỂ CHỈNH SỬA, BẠN CÓ CHẮC CHẮN KHÓA ĐỀ NÀY ?");
        if(choose == JOptionPane.YES_OPTION){
            
            exam.setStt(false);
            if(new ExamDAO().update(exam)){
                JOptionPane.showMessageDialog(this, "ĐỀ THI ĐÃ ĐƯỢC KHÓA VÀ KHÔNG THỂ CHỈNH SỬA");
            }else{
                JOptionPane.showMessageDialog(this,"GẶP LỖI, THAY ĐỔI TRẠNG THÁI THẤT BẠI");
            }
        }
        this.getData();
        
    }//GEN-LAST:event_btn_sttActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addQ;
    private javax.swing.JButton btn_addQ2;
    private javax.swing.JButton btn_deleteQ;
    private javax.swing.JButton btn_stt;
    private javax.swing.JComboBox<String> cbo_examid;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_examid;
    private javax.swing.JLabel lbl_soluong;
    private javax.swing.JTable tbl_danhsach;
    private javax.swing.JTable tbl_list2;
    private javax.swing.JTextField txt_debai;
    private javax.swing.JTextField txt_newE;
    // End of variables declaration//GEN-END:variables
}
